### ISSUE TITLE
Paste image doesn't work. Does it need additional config?

### ISSUE THREAD

**Issue by skironDotNet** [Chaosmeister/PITM#3]
![image](https://user-images.githubusercontent.com/2981715/144476778-57d7aa50-48c7-4904-a161-46ade301d26d.png)

**Comment by Chaosmeister** [comment]
hey  
I just updated the readme to hint to the required change to load the inline images

**Comment by Jieiku** [comment]
I believe this is because he does not have MarkdownPlus, you may want to add a note about that as well to your github readme, I would put it in BIG BOLD lettering toward the top because people will still miss it, LOL!

I wonder if kanboard plugin system has provisioning for displaying dependencies. Like if you do not have the MarkdownPlus plugin then maybe when you install this PITM plugin it could display a message like dependency MarkdownPlus is missing.

https://github.com/creecros/MarkdownPlus
